/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 헬스체크 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["HealthStatus"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원가입 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignupRequest"];
                };
            };
            responses: {
                /** @description 회원가입 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["TokenResponse"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description DUPLICATE_EMAIL */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 로그인 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["TokenResponse"];
                        };
                    };
                };
                /** @description INVALID_CREDENTIALS */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 토큰 갱신 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description 갱신 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["TokenResponse"];
                        };
                    };
                };
                /** @description INVALID_TOKEN | EXPIRED_TOKEN */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 로그아웃 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 조회 (전 역할) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["UserMeResponse"];
                        };
                    };
                };
                /** @description USER_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/counselors/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 자격 증빙 업로드 (ROLE_COUNSELOR) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @enum {string} */
                        type?: "ENROLLMENT" | "DEGREE" | "LICENSE" | "ID";
                        /**
                         * Format: binary
                         * @description pdf/jpg/png, 최대 10MB
                         */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description PENDING 상태로 접수 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["CredentialUploadResponse"];
                        };
                    };
                };
                /** @description FILE_EMPTY | INVALID_FILE_TYPE | FILE_TOO_LARGE */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description FILE_UPLOAD_FAILED */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/counselors/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 프로필 조회 (ROLE_COUNSELOR) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 프로필 + status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["CounselorProfileResponse"];
                        };
                    };
                };
                /** @description COUNSELOR_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** 내 프로필 수정 (ROLE_COUNSELOR, status==APPROVED만 허용) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CounselorProfileUpdateRequest"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["CounselorProfileResponse"];
                        };
                    };
                };
                /** @description INVALID_INPUT (금칙어 — ADR-8) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description PROFILE_NOT_APPROVED */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 자격 심사 대기열 조회 (ROLE_ADMIN) */
        get: {
            parameters: {
                query?: {
                    status?: "PENDING" | "APPROVED" | "REJECTED";
                    page?: components["parameters"]["PageParam"];
                    size?: components["parameters"]["SizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 심사 항목 페이지 (presigned URL 포함) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["PageMeta"] & {
                                content?: components["schemas"]["CredentialListItem"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/credentials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 자격 심사 처리 (ROLE_ADMIN) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CredentialReviewRequest"];
                };
            };
            responses: {
                /** @description 승인 시 프로필 APPROVED + 이메일 발송 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"];
                    };
                };
                /** @description REJECT_REASON_REQUIRED */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description CREDENTIAL_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description CREDENTIAL_ALREADY_REVIEWED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/counselors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 상담사 탐색 (permitAll, APPROVED + is_listed만 노출) */
        get: {
            parameters: {
                query?: {
                    specialty?: string;
                    priceMin?: number;
                    priceMax?: number;
                    availableDate?: string;
                    page?: components["parameters"]["PageParam"];
                    size?: components["parameters"]["SizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 상담사 목록 페이지 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["PageMeta"] & {
                                content?: components["schemas"]["CounselorSearchItem"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/counselors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 상담사 상세 (permitAll) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 프로필 + 평점 요약 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["CounselorDetailResponse"];
                        };
                    };
                };
                /** @description COUNSELOR_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/counselors/me/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 내 가용시간 전체 치환 (ROLE_COUNSELOR) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AvailabilityUpsertRequest"];
                };
            };
            responses: {
                /** @description 치환 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"];
                    };
                };
                /** @description INVALID_TIME_RANGE */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/counselors/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 상담사 가용 슬롯 조회 (permitAll, 기예약 제외) */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 날짜별 슬롯 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["AvailabilitySlotsResponse"];
                        };
                    };
                };
                /** @description COUNSELOR_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 예약 목록 조회 (ROLE_CLIENT/ROLE_COUNSELOR, 역할은 토큰에서 판별) */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    page?: components["parameters"]["PageParam"];
                    size?: components["parameters"]["SizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 본인 예약 페이지 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["PageMeta"] & {
                                content?: components["schemas"]["SessionListItem"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 예약 생성 (ROLE_CLIENT) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SessionCreateRequest"];
                };
            };
            responses: {
                /** @description PENDING_PAYMENT 상태로 생성 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["SessionCreateResponse"];
                        };
                    };
                };
                /** @description SESSION_PAST_TIME */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description SESSION_TIME_CONFLICT (ADR-2) | COUNSELOR_NOT_APPROVED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questionnaires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 문진표 작성 (ROLE_CLIENT, 본인 세션) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QuestionnaireCreateRequest"];
                };
            };
            responses: {
                /** @description isAccessible=false로 생성 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["QuestionnaireCreateResponse"];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description QUESTIONNAIRE_ALREADY_SUBMITTED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questionnaires/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문진표 조회 (ADR-3 접근 매트릭스 — CLIENT 본인/ADMIN/COUNSELOR(isAccessible) 분기) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["QuestionnaireResponse"];
                        };
                    };
                };
                /** @description QUESTIONNAIRE_NOT_ACCESSIBLE */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description QUESTIONNAIRE_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/initialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 결제 초기화 (ROLE_CLIENT, 본인 세션. 금액은 서버가 상담사 가격에서 계산) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        sessionId: number;
                    };
                };
            };
            responses: {
                /** @description 결제 주문 생성 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["PaymentInitializeResponse"];
                        };
                    };
                };
                /** @description SESSION_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description PAYMENT_ALREADY_COMPLETED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 결제 승인 확정 (ROLE_CLIENT, ADR-4 이중 금액검증 + 멱등) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentConfirmRequest"];
                };
            };
            responses: {
                /** @description 승인 완료 — session AWAITING_CONFIRM + ChatRoom 생성 + questionnaire.isAccessible=true */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["PaymentConfirmResponse"];
                        };
                    };
                };
                /** @description PAYMENT_AMOUNT_MISMATCH (토스 호출 전 1차 검증 실패 — 토스 미호출) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description PAYMENT_NOT_FOUND 이후 상태 충돌 또는 paymentKey 불일치 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description PAYMENT_GATEWAY_ERROR */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description PAYMENT_GATEWAY_TIMEOUT */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 토스 웹훅 수신 (permitAll + 서명검증, PaymentCompletionProcessor를 confirm과 공유 — ADR-4) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description 항상 200 (PG 재시도 폭주 방지). 서명 불일치만 예외 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description INVALID_WEBHOOK_SIGNATURE */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 상담 요청 수락 (ROLE_COUNSELOR 본인, ADR-0 AWAITING_CONFIRM → CONFIRMED) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CONFIRMED로 전이 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"];
                    };
                };
                /** @description INVALID_SESSION_STATUS */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/sessions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 상담 요청 거절 (ROLE_COUNSELOR 본인 → REJECTED + 전액 refunds INSERT + 이메일) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rejectReason: string;
                    };
                };
            };
            responses: {
                /** @description REJECTED로 전이 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"];
                    };
                };
                /** @description REJECT_REASON_REQUIRED */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description INVALID_SESSION_STATUS */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/admin/payments/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 관리자 강제 환불 (ROLE_ADMIN, 부분환불 지원, Idempotency-Key) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 미지정 시 전액 */
                        amount?: number;
                    };
                };
            };
            responses: {
                /** @description 환불 처리 완료 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"];
                    };
                };
                /** @description REFUND_AMOUNT_EXCEEDED */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description REFUND_FAILED */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 채팅방 목록 (참여자) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["ChatRoomListItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat-rooms/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 메시지 이력 조회 (커서 기반 — ADR-10) */
        get: {
            parameters: {
                query?: {
                    /** @description 이 messageId보다 이전 메시지를 조회 (미지정 시 최신부터) */
                    before?: number;
                    size?: number;
                };
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["ChatMessageListResponse"];
                        };
                    };
                };
                /** @description NOT_CHAT_PARTICIPANT */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description CHAT_ROOM_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 메시지 전송 (참여자, REST 송신 — ADR-9. WebSocket 송신 경로는 폐기) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatMessageSendRequest"];
                };
            };
            responses: {
                /** @description 저장 후 /topic/chat/{roomId}로 브로드캐스트 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["ChatMessage"];
                        };
                    };
                };
                /** @description EMPTY_MESSAGE */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description NOT_CHAT_PARTICIPANT */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 리뷰 목록 조회 (permitAll, 익명 시 authorName null) */
        get: {
            parameters: {
                query: {
                    counselorId: number;
                    page?: components["parameters"]["PageParam"];
                    size?: components["parameters"]["SizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["PageMeta"] & {
                                content?: components["schemas"]["ReviewListItem"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 리뷰 작성 (ROLE_CLIENT, 본인 COMPLETED 세션, 금칙어 검증 — ADR-8) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewCreateRequest"];
                };
            };
            responses: {
                /** @description 작성 완료 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"];
                    };
                };
                /** @description SESSION_NOT_COMPLETED */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description REVIEW_ALREADY_EXISTS */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 상담 완료 처리 (ROLE_COUNSELOR, CONFIRMED → COMPLETED만. 자동완료 스케줄러 병행) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "COMPLETED";
                    };
                };
            };
            responses: {
                /** @description COMPLETED로 전이 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"];
                    };
                };
                /** @description INVALID_SESSION_STATUS */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/counselors/me/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정산 내역 (ROLE_COUNSELOR) */
        get: {
            parameters: {
                query: {
                    month: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["EarningsResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 예약 취소 (ROLE_CLIENT 또는 ROLE_COUNSELOR — 환불율은 §5 취소 환불율 표) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 취소 처리 완료 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["SessionCancelResponse"];
                        };
                    };
                };
                /** @description SESSION_ALREADY_CANCELLED | INVALID_SESSION_STATUS */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/report-no-show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 노쇼 신고 (ROLE_CLIENT, 시작시각 경과 후) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description 분쟁 접수 (OPEN) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["NoShowReportResponse"];
                        };
                    };
                };
                /** @description SESSION_NOT_STARTED */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description DISPUTE_ALREADY_EXISTS */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 분쟁 목록 조회 (ROLE_ADMIN) */
        get: {
            parameters: {
                query?: {
                    status?: "OPEN" | "RESOLVED_REFUND" | "RESOLVED_REJECT";
                    page?: components["parameters"]["PageParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"] & {
                            data?: components["schemas"]["PageMeta"] & {
                                content?: components["schemas"]["DisputeListItem"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/disputes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 분쟁 해결 (ROLE_ADMIN — REFUND 시 전액환불 실행 + 페널티 기록, ADR-7) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        resolution: "REFUND" | "REJECT";
                        resolutionNote?: string;
                    };
                };
            };
            responses: {
                /** @description 해결 처리 완료 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEnvelope"];
                    };
                };
                /** @description DISPUTE_ALREADY_RESOLVED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 성공 응답 공통 래퍼. data는 각 엔드포인트별로 오버라이드됨. */
        ApiResponseEnvelope: {
            /** @example true */
            success?: boolean;
            message?: string | null;
            data?: Record<string, never> | null;
        };
        /** @description 실패 응답 공통 포맷 (P1.5부터 code 필드 추가 — GlobalExceptionHandler) */
        ErrorResponse: {
            /** @example false */
            success: boolean;
            /** @description ErrorCode enum name (예 SESSION_TIME_CONFLICT) */
            code: string;
            message: string;
        };
        PageMeta: {
            page?: number;
            size?: number;
            totalElements?: number;
            totalPages?: number;
        };
        HealthStatus: {
            /** @example UP */
            status?: string;
            /** @example MindFit API */
            service?: string;
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            /** Format: date */
            birthDate?: string | null;
            /**
             * @description ROLE_ADMIN 가입은 서버에서 차단됨
             * @enum {string}
             */
            role: "ROLE_CLIENT" | "ROLE_COUNSELOR";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        TokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            userId?: number;
            /** @enum {string} */
            role?: "ROLE_CLIENT" | "ROLE_COUNSELOR" | "ROLE_ADMIN";
        };
        UserMeResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            name?: string;
            /** @enum {string} */
            role?: "ROLE_CLIENT" | "ROLE_COUNSELOR" | "ROLE_ADMIN";
        };
        CredentialUploadResponse: {
            /** Format: int64 */
            credentialId?: number;
            /** @enum {string} */
            status?: "PENDING";
        };
        CounselorProfileResponse: {
            /** Format: int64 */
            userId?: number;
            bio?: string;
            photoUrl?: string;
            pricePerSession?: number;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED";
            specialties?: string[];
            approachTypes?: string[];
            sessionTypes?: ("CHAT" | "VIDEO_LINK")[];
        };
        CounselorProfileUpdateRequest: {
            bio?: string;
            photoUrl?: string;
            pricePerSession?: number;
            specialtyIds?: number[];
            approachTypeIds?: number[];
            sessionTypes?: ("CHAT" | "VIDEO_LINK")[];
        };
        CredentialListItem: {
            /** Format: int64 */
            credentialId?: number;
            /** Format: int64 */
            counselorId?: number;
            counselorName?: string;
            /** @enum {string} */
            type?: "ENROLLMENT" | "DEGREE" | "LICENSE" | "ID";
            /** @description presigned URL */
            fileUrl?: string;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED";
            /** Format: date-time */
            createdAt?: string;
        };
        CredentialReviewRequest: {
            /** @enum {string} */
            action: "APPROVE" | "REJECT";
            /** @description action=REJECT일 때 필수 */
            rejectReason?: string;
        };
        CounselorSearchItem: {
            /** Format: int64 */
            counselorId?: number;
            name?: string;
            photoUrl?: string;
            specialties?: string[];
            pricePerSession?: number;
            /** Format: float */
            ratingAvg?: number;
            reviewCount?: number;
        };
        CounselorDetailResponse: components["schemas"]["CounselorSearchItem"] & {
            bio?: string;
            approachTypes?: string[];
            sessionTypes?: string[];
        };
        AvailabilityUpsertRequest: {
            slots?: {
                /** @enum {string} */
                type?: "WEEKLY" | "SPECIFIC";
                dayOfWeek?: string | null;
                /** Format: date */
                date?: string | null;
                /** @example 14:00 */
                startTime?: string;
                /** @example 15:00 */
                endTime?: string;
                isBlocked?: boolean;
            }[];
        };
        AvailabilitySlotsResponse: {
            /** Format: date */
            date?: string;
            slots?: {
                startTime?: string;
                endTime?: string;
                available?: boolean;
            }[];
        };
        SessionCreateRequest: {
            /** Format: int64 */
            counselorId: number;
            /** Format: date-time */
            scheduledAt: string;
            durationMin: number;
            /** @enum {string} */
            sessionType: "CHAT" | "VIDEO_LINK";
        };
        SessionCreateResponse: {
            /** Format: int64 */
            sessionId?: number;
            /** @enum {string} */
            status?: "PENDING_PAYMENT";
            amount?: number;
        };
        SessionListItem: {
            /** Format: int64 */
            sessionId?: number;
            /** Format: int64 */
            counselorId?: number;
            /** Format: int64 */
            clientId?: number;
            /** Format: date-time */
            scheduledAt?: string;
            status?: components["schemas"]["SessionStatus"];
        };
        /**
         * @description ADR-0 상태머신 (§3 참조)
         * @enum {string}
         */
        SessionStatus: "PENDING_PAYMENT" | "AWAITING_CONFIRM" | "CONFIRMED" | "COMPLETED" | "REJECTED" | "CANCELLED_BY_CLIENT" | "CANCELLED_BY_COUNSELOR" | "NO_SHOW";
        QuestionnaireCreateRequest: {
            /** Format: int64 */
            sessionId: number;
            mainConcern: string;
            severity: number;
            durationText?: string;
            priorExperience?: string;
            goal?: string;
            additionalNote?: string;
        };
        QuestionnaireCreateResponse: {
            /** Format: int64 */
            questionnaireId?: number;
            /** @example false */
            isAccessible?: boolean;
        };
        QuestionnaireResponse: components["schemas"]["QuestionnaireCreateRequest"] & {
            /** Format: int64 */
            questionnaireId?: number;
            isAccessible?: boolean;
            /** Format: date-time */
            submittedAt?: string;
        };
        PaymentInitializeResponse: {
            /** Format: int64 */
            paymentId?: number;
            orderId?: string;
            /** @description 서버가 상담사 가격에서 계산 (클라이언트 입력 무시) */
            amount?: number;
            orderName?: string;
        };
        PaymentConfirmRequest: {
            paymentKey: string;
            orderId: string;
            amount: number;
        };
        PaymentConfirmResponse: {
            /** @enum {string} */
            status?: "COMPLETED";
            /** Format: int64 */
            chatRoomId?: number;
        };
        ChatRoomListItem: {
            /** Format: int64 */
            roomId?: number;
            partnerName?: string;
            lastMessage?: string | null;
            unreadCount?: number;
        };
        ChatMessage: {
            /** Format: int64 */
            messageId?: number;
            /** Format: int64 */
            chatRoomId?: number;
            /** Format: int64 */
            senderId?: number;
            content?: string;
            /** @enum {string} */
            messageType?: "TEXT" | "IMAGE" | "LINK";
            /** @description 클라이언트 생성 UUID — 중복 제거용 (ADR-9) */
            clientMessageId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ChatMessageListResponse: {
            messages?: components["schemas"]["ChatMessage"][];
            hasNext?: boolean;
        };
        ChatMessageSendRequest: {
            content: string;
            /** @enum {string} */
            messageType: "TEXT" | "IMAGE" | "LINK";
            /** Format: uuid */
            clientMessageId: string;
        };
        ReviewCreateRequest: {
            /** Format: int64 */
            sessionId: number;
            rating: number;
            content?: string;
            /** @default false */
            isAnonymous: boolean;
        };
        ReviewListItem: {
            /** Format: int64 */
            reviewId?: number;
            /** @description isAnonymous=true면 null */
            authorName?: string | null;
            rating?: number;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        EarningsResponse: {
            sessionCount?: number;
            grossAmount?: number;
            /** @description 수수료 20% */
            fee?: number;
            /** @description 정산액 = 금액 × 0.8 */
            netAmount?: number;
            sessions?: components["schemas"]["SessionListItem"][];
        };
        SessionCancelResponse: {
            refundAmount?: number;
            /**
             * Format: float
             * @description CLIENT 24h 이상 전=1.0 / 24h 미만=0.5 / 시작 후=취소 불가. COUNSELOR=시점 무관 1.0
             */
            refundRate?: number;
        };
        NoShowReportResponse: {
            /** Format: int64 */
            disputeId?: number;
            /** @enum {string} */
            status?: "OPEN";
        };
        DisputeListItem: {
            /** Format: int64 */
            disputeId?: number;
            /** Format: int64 */
            sessionId?: number;
            /** Format: int64 */
            reporterId?: number;
            description?: string;
            /** @enum {string} */
            status?: "OPEN" | "RESOLVED_REFUND" | "RESOLVED_REJECT";
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: {
        /** @description INVALID_INPUT — 요청 필드 검증 실패 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description INVALID_TOKEN | EXPIRED_TOKEN */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description ACCESS_DENIED | FORBIDDEN_ROLE */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdParam: number;
        PageParam: number;
        SizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
